fuckapp/urls.py
from django.urls import path
from . import views

app_name = "fuckapp"
urlpatterns = [
    path('', views.index, name="index"),
    path('verify', views.code_verify, name="code_verify"),
]

myProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('myadmin/', include('users.urls')),
    path('', include('fuckapp.urls')),
]

tasks/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

tasks/urls.py
from django.urls import path, re_path
from . import views

# namespace
app_name = 'tasks'

urlpatterns = [
    # Create a task
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    # Retrieve task list
    path('', views.TaskListView.as_view(), name='task_list'),
    # Retrieve single task object
    re_path(r'^(?P<pk>\d+)/$', views.TaskDetailView.as_view(), name='task_detail'),
    # Update a task
    re_path(r'^(?P<pk>\d+)/update/$', views.TaskUpdateView.as_view(), name='task_update'),
    # Delete a task
    re_path(r'^(?P<pk>\d+)/delete/$', views.TaskDeleteView.as_view(), name='task_delete')
]

users/urls.py
from django.urls import path, re_path
from . import views


app_name = 'users'
urlpatterns = [
    path('', views.UserAdminTableView.as_view(), name='user_admin'),
    path('users/create/', views.UserCreateView.as_view(), name='user_create'),
    path('users/<int:pk>/update/', views.UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
]

fuckapp/models.py
from django.db import models


# Create your models here.
class InvitationCode(models.Model):
    code = models.CharField(verbose_name="邀请码", max_length=10, unique=True)
    expire = models.DateTimeField(verbose_name="过期时间")

    def __str__(self):
        return self.code

tasks/models.py
from django.db import models


class Status(models.TextChoices):
    UNSTARTED = 'u', "Not started yet"
    ONGOING = 'o', "Ongoing"
    FINISHED = 'f', "Finished"


class Task(models.Model):
    name = models.CharField(verbose_name="Task name", max_length=65, unique=True)
    status = models.CharField(verbose_name="Task status", max_length=1,
                              choices=Status.choices)

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth import get_user_model
User = get_user_model()

fuckapp/forms.py
from django import forms
from .models import InvitationCode

class InvitationCodeForm(forms.ModelForm):
    class Meta:
        model = InvitationCode
        fields = ("code",)

tasks/forms.py
from .models import Task
from django import forms


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"

users/forms.py
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        # 自定义使用哪个模型和哪些字段来创建和更新用户
        model = User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

        widgets = {
            'password': forms.PasswordInput(),
        }

fuckapp/views.py
from django.shortcuts import render, redirect
from .models import InvitationCode
from .forms import InvitationCodeForm
from django.utils.timezone import now
from django.contrib import messages


# 获取用户IP地址
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


# 验证用户邀请码。邀请码正确则以用户IP设为session key，值True，会话持续60秒
def code_verify(request):
    session_key = "user_ip_{}".format(get_client_ip(request))
    if request.method == "POST":
        code = request.POST.get("code", "")
        code_obj = InvitationCode.objects.filter(code=code, expire__gt=now()).first()
        if code_obj:
            request.session[session_key] = True
            request.session.set_expiry(60)  # 会话有效时间60秒。60秒后需重新提交邀请码。
            messages.add_message(request, messages.SUCCESS, '恭喜你已成功通过验证码验证。本次会话60秒有效。')
        else:
            messages.add_message(request, messages.WARNING, '你的邀请码错误或已经过期。请重新输入。')
            if session_key in request.session:
                del request.session[session_key]

    return redirect("/")  # 跳转到index页面


# 需要有效会话才能访问内容页面，否则展示输入邀请码的表单
def index(request):
    session_key = "user_ip_{}".format(get_client_ip(request))
    # 如果用户IP地址在session里，且值为True则展示隐藏内容
    if session_key in request.session and request.session[session_key]:
        return render(request, "fuckapp/index.html")
    else:
        form = InvitationCodeForm()
        return render(request, "fuckapp/index.html", {"form": form, })

tasks/views.py
from django.urls import reverse_lazy, reverse
from .models import Task
from .forms import TaskForm
from django.views.generic import ListView, DetailView, \
    CreateView, UpdateView, DeleteView


class TaskListView(ListView):
    model = Task
    context_object_name = 'tasks'


class TaskDetailView(DetailView):
    model = Task


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:task_list')

users/views.py
# 核心Django模块，比如Mixins和通用视图
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import User

# django fitler和django_tables2提供的Mixins
from django_tables2 import SingleTableView, RequestConfig
from django_filters.views import FilterView

# filters.py定义了用哪些字段对模型进行过滤
from .filters import UserFilter

# tables.py定义了用哪些字段将在表格中展示
from .tables import UserTable

# forms.py定义了用哪些字段创建或更新用户
from .forms import UserForm


# 管理用户主界面
class UserAdminTableView(LoginRequiredMixin, SingleTableView, FilterView):
    filter = None
    # 使用UserFilter过滤
    filter_class = UserFilter
    # 使用UserTable展示数据
    table_class = UserTable
    template_name = 'users/user_admin.html'

    # 获取过滤后的查询集
    def get_queryset(self, **kwargs):
        qs = User.objects.all().order_by('-id')
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        return self.filter.qs

    # 将查询集与table实例集合，提供filter和table两个变量前端渲染
    # 每页5条记录
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        t = self.table_class(data=self.get_queryset())
        RequestConfig(self.request, paginate={"per_page": 5}).configure(t)
        context['filter'] = self.filter
        context['table'] = t
        return context


# create
class UserCreateView(LoginRequiredMixin, CreateView):
    model = User
    template_name = 'users/user_form.html'
    form_class = UserForm
    success_url = reverse_lazy('users:user_admin')


# update
class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'users/user_form.html'
    form_class = UserForm
    success_url = reverse_lazy('users:user_admin')


# Delete
class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'users/user_confirm_delete.html'
    success_url = reverse_lazy('users:user_admin')

fuckapp/templates/fuckapp/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Django Session例子</title>
    </head>
<body>
    <h3>需要邀请码才能访问此页面</h3>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if form %}
    <form action="{% url 'fuckapp:code_verify' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">提交</button>
    </form>
    {% else %}
        <p>这部分属于隐藏内容。如果你能看到这个内容，说明你邀请码正确且会话未过期。</p>
    {% endif %}

</body>
</html>

tasks/templates/tasks/task_confirm_delete.html
 <!DOCTYPE html>
<html lang="en">
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</html>

tasks/templates/tasks/task_detail.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <title>Task Detail</title>
 </head>
 <body>
 <p> Task Name: {{ task.name }} | <a href="{% url 'tasks:task_update' task.id %}">Update</a> |
     <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>
 </p>
 <p> Task Status: {{ task.get_status_display }} </p>
 <p> <a href="{% url 'tasks:task_list' %}">View All Tasks</a> |
     <a href="{% url 'tasks:task_create'%}">New Task</a>
 </p>
 </body>
 </html>

tasks/templates/tasks/task_form.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <title>{% if object %}Edit Task {% else %} Create New Task {% endif %}</title>
 </head>
 <body>
 <h3>{% if object %}Edit Task {% else %} Create New Task {% endif %}</h3>
     <form action="" method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ form.as_p }}
         <p><input type="submit" class="btn btn-success" value="Submit"></p>
     </form>
 </body>
 </html>

tasks/templates/tasks/task_list.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <title>Task List</title>
 </head>
 <body>
 <h3>Task List</h3>
 {% for task in tasks %}
     <p>{{ forloop.counter }}. {{ task.name }} - {{ task.get_status_display }}
         (<a href="{% url 'tasks:task_update' task.id %}">Update</a> |
         <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>)
     </p>
 {% endfor %}

 <p> <a href="{% url 'tasks:task_create' %}"> + Add A New Task</a></p>
 </body>
 </html>

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
        content="">
    <title>Django Filter + Django Tables 2 Admin</title>

    <!-- using online links -->
   <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
   <style>
	@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,500,700);
	body, table, th, tr, td, p
	{
	  font-family: 'Source Sans Pro', sans-serif;
	  color:#666;
	}
	body a { color:#666 }
	body a:hover { text-decoration:none;}

</style>


</head>

<body class="bg-light">
        <!-- head  -->
         <div class="bg-secondary">
			 <div class="container-fluid px-0" style="max-width: 1200px;">
                 <!-- right-top-navbar  -->
				<nav class="navbar row">
				   <div class="col-6">
				     <a class="navbar-brand text-white" href="#">
						用户管理后台
					</a>
					</div>

					<!-- User profile dropdown -->
					<div class="dropdown col-6 text-right">
                        {% if not request.user.is_authenticated %}
					         <small><a href="/myadmin/" class="btn btn-sm btn-info">Login</a></small>
                        {% else %}
							 <a class="dropdown-toggle text-white" href="#" id="dropdown-user" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								{{ request.user.username }}
							</a>
                            <div class="dropdown-menu dropdown-menu-right mr-2 mt-2" aria-labelledby="dropdown-user">
								<a class="dropdown-item text-muted" href="/myadmin/">Log Out</a>
                            </div>
                        {% endif %}
                    </div>

				  </nav>
			 </div>
        </div>
		 <!-- End of head  -->



		<div class="container-fluid py-0 mt-3" style="max-width: 1200px;">
	          <!-- Start of x_box 1 -->
              <div class="mx-md-3">
				  {% block content %}

                {% endblock %}
                </div><!-- End of x_box -->
          </div>


    <!-- using online scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous">
    </script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


</body>
</html>

users/templates/users/bs4_tables2.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="table-wrapper mt-2">
    {% block table %}
    <div class="table-responsive">
        <table {% render_attrs table.attrs class="table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead {{ table.attrs.thead.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <th {{ column.attrs.th.as_html }}>
                        {% if column.orderable %}
                        <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}"><i class="bi bi-chevron-expand"></i>{{ column.header }} </a>
                        {% else %}
                            {{ column.header }}
                        {% endif %}
                    </th>
                {% endfor %}
                </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            {% if table.has_footer %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
            </tfoot>
            {% endif %}
            {% endblock table.tfoot %}
        </table>
    </div>
    {% endblock table %}

    {% block pagination %}
        {% if table.page and table.paginator.num_pages > 1 %}
        <nav aria-label="Table navigation ">
            <ul class="pagination justify-content-center float-md-left">
            {% if table.page.has_previous %}
                {% block pagination.previous %}
                <li class="previous page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link">
                        <span aria-hidden="true">&laquo;</span>

                    </a>
                </li>
                {% endblock pagination.previous %}
            {% endif %}
            {% if table.page.has_previous or table.page.has_next %}
            {% block pagination.range %}
            {% for p in table.page|table_page_range:table.paginator %}
                <li class="page-item{% if table.page.number == p %} active{% endif %}">
                    <a class="page-link" {% if p != '...' %}href="{% querystring table.prefixed_page_field=p %}"{% endif %}>
                        {{ p }}
                    </a>
                </li>
            {% endfor %}
            {% endblock pagination.range %}
            {% endif %}
            {% if table.page.has_next %}
                {% block pagination.next %}
                <li class="next page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endblock pagination.next %}
            {% endif %}
            </ul>

              <div class="float-md-right d-none d-md-block">
             <p>{% trans 'Per page' %}: [ <a href="{% querystring 'per_page'=20 %}">20</a> |
               <a href="{% querystring 'per_page'=50 %}">50</a>
                | <a href="{% querystring 'per_page'=100 %}">100</a> ]
            </p>
           </div>
        </nav>

        {% endif %}

    {% endblock pagination %}
</div>
{% endblock table-wrapper %}

users/templates/users/bs_form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
<div class="alert alert-warning alert-dismissible fade in" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
          </button>
    {% for error in form.non_field_errors %} {{ error }} {% endfor %}
</div>
{% endif %}

{% for hidden_field in form.hidden_fields %} {{ hidden_field }} {% endfor %}
{% for field in form.visible_fields %}

      <div class="form-group{% if field.errors %} invalid{% endif %}">
            {{ field.label_tag }}
             {% render_field field class="form-control"%}
              {% if field.help_text %}
                  <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
              {% for error in field.errors %}
              <p class="text-danger small">{{ error }}</p>
            {% endfor %}
        </div>
{% endfor %}

users/templates/users/user_admin.html
{% extends 'users/base.html' %}
{% load django_tables2 %}

{% block content %}
     <div class="align-items-center row">
             <div class="col-6 pt-2">
                    <h5>管理用户</h5>
             </div>

             <div class="col-6">
                     <span class="dropdown float-right">
                        <a href="{% url 'users:user_create' %}"><button type="button" id="modal-create-btn" class="btn btn-sm btn-success"
                                 data-toggle="tooltip" data-placement="top" title="添加用户">
                         <i class="bi bi-plus"></i>添加用户</button></a>

                    </span>

              </div>
     </div>


    <div class="align-items-center py-1 row bg-white">
             <div class="col-sm-6 col-md-3">
                 <form class="" action="" method="get">
                     <div class="input-group">
                         <label>
                             <input type="text" name="query" class="form-control search-menu"
                                autocomplete="off" placeholder="关键词" value="{{ request.GET.query }}">
                         </label>
                         <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="bi bi-search" aria-hidden="true"></i>
                                </button>
                         </div>
                     </div>
                 </form>
             </div>

              <div class="col-sm-6 col-md-9 mt-1">
                  <span class="dropdown float-md-right">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle my-0" data-toggle="dropdown" aria-expanded="false">
                         <i class="bi bi-funnel"></i> 过滤
                     </button>
                     <div class="dropdown-menu dropdown-menu-right px-3 mt-2" role="menu" style="width:280px">
                         <form class="form-horizontal" role="form" autocomplete="off">
                             {% include 'users/bs_form.html' with form=filter.form %}
                             <button type="submit" class="btn btn-sm btn-info form-control">确定</button>
                         </form>
                     </div>

                      <a href="{{ request.path }}" class="btn btn-light btn-sm">
                      <i class="bi bi-backspace-reverse"></i> 重置
                      </a>

                    </span>
             </div>

         </div>
        {% render_table table %}

{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'users/base.html' %}
{% block content %}

 <div class="x_title align-items-center row bg-white rounded-top">
     <div class="col-6 pt-2">
         <h5>删除用户</h5>
     </div>
 </div>

<div class="align-items-center py-1 row bg-white pl-3 pb-3 border-top border-gray rounded-bottom">
    <form method="post">{% csrf_token %}
        <p>你确定要删除用户"{{ user }}"吗?</p>
        <input type="submit" value="Confirm" class="btn btn-warning" />
    </form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'users/base.html' %}
{% block content %}
 <div class="align-items-center row bg-white rounded-top">
     <div class="col-6 pt-2">
         <h5>{% if object %}编辑用户 {% else %} 添加用户 {% endif %}</h5>
     </div>
 </div>

<div class="align-items-center py-1 row bg-white pl-3 pb-3 border-top border-gray rounded-bottom">
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
     {% include 'users/bs_form.html' with form=form %}
    <p><input type="submit" class="btn btn-success" value="Submit"></p>
    </form>
</div>
{% endblock %}